name: banana_snack_application
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.6 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter

dev_dependencies: 
  http: ^1.1.0
  url_launcher: ^6.1.14
  flutter_launcher_icons: ^0.13.1
  google_fonts: ^6.1.0
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/logos/
    - assets/icons/
    - assets/images/
